//<auto-generated/>

namespace WpfApp1.Entity.WeekNumber
{
    using System;
    using System.Collections.Generic;
    using System.Linq;
    using System.Text;
    using System.Threading.Tasks;
    using Calender.Entitey;

    public class WeekTitleSun : WeekItem
    {
    }
}
