//<auto-generated/>

using Calender.Entitey;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace WpfApp1.Entity.WeekNumber
{
    public class WeekTitleMon : WeekItem
    {
    }
}
